export { default as Hero } from "./Hero";
export { default as Services } from "./Services";
export { default as Footer } from "./Footer";
export { default as Projects } from "./Projects";
export { default as ProofState } from "./ProofState";
export { default as Clients } from "./Clients";
export { default as Skills } from "./Skills";
export { default as Contact } from "./Contact";
export { default as About } from "./About";
